### ISSUE TITLE
Config crashes if profile is not set with config in WeeklySchedule plugin

### ISSUE THREAD

**Issue by Nikjee** [dm94/DmPlugin#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot and plugin version?

- [X] I have confirmed i'm running the latest bot version

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

I you set up a weekly schedule without providing config to profile it will crash. For example if you set any profile without providing any settings to it then it will crash because it can't find the config

### Expected Behavior

Expected to use the default settings of the bot, like i wanted basic settings when the bot should turn off and just keep playing on default config

### Steps To Reproduce

1. Run bot with your config
2. Enable Weekly Schedule plugin with default settings, not setting profiles and filling the time table with it
3l After enabling the plugin it will "crash" on non existing config, after it you have to edit manually your own config to turn off the plugin

### Screenshots, Video, or other media

Don't have it right now since i already added settings to profile

### Bot Version

v1.131.2

### Plugin version

v2.3.2

**Comment by dm94** [comment]
It is correct that if you have not configured a profile you get an error. If you want it to use the default profile, configure the default profile.

**Comment by Nikjee** [comment]
> It is correct that if you have not configured a profile you get an error. If you want it to use the default profile, configure the default profile.

Well if i don't need to configure anything can't you just set it to use what's currently in use?

**Comment by dm94** [comment]
> > It is correct that if you have not configured a profile you get an error. If you want it to use the default profile, configure the default profile.
> 
> Well if i don't need to configure anything can't you just set it to use what's currently in use?

but then that would be a tailor-made logic, if it is obligatory to configure a configuration, it is obligatory.

**Comment by dm94** [comment]
I have added an initial value to the selected profile so that there are no errors https://github.com/dm94/DmPlugin/commit/35f2f724cb53331973e2aa8ea0bd830c53391825

**Comment by Nikjee** [comment]
> I have added an initial value to the selected profile so that there are no errors [35f2f72](https://github.com/dm94/DmPlugin/commit/35f2f724cb53331973e2aa8ea0bd830c53391825)

If profile is not set and field are empty it will load empty config instead of using existing one which is currently in use
