### ISSUE TITLE
eternal black light module, seperate settings 

### ISSUE THREAD

**Issue by timmynl007** [dm94/DmPlugin#206]
i would like to have seperate settings for the eternal gate, and for the 'farming cpu' stage
for example seperate 
-pet settings(like locator to farm cpu)
-drone formation settings(in the gate i use moth,  prefer drill on cpu farm)
-use of energy leach/techs when attacking/getting hit by invoke when my hp get lower then x amount 
 
<3

**Comment by dm94** [comment]
This plugin has nothing to do with what you are asking for, so what you are asking for is not from this plugin.
